[input_parameters]
length = 0.01
amplitude_perturbation_x = 5e-7
wavenumber_electrons_x = 1
grid_points_per_Debye_length = 0.6
vth_electrons_over_c_x = 0.05
ion_temperature_over_electron_temperature_x = 0.01
timestep_over_spatialstep_times_c = 1.0
electron_drift_speed_x = 6e7
velocity_plus_minus_electrons_x = true
print_info = false
seed = 1701
external_electric_field_amplitude = 0
external_electric_field_wavenumber = 0
electron_charge_over_elementary_charge = -1
ion_charge_over_elementary_charge = 1
ion_mass_over_proton_mass = 1
relativistic = false
tolerance_Picard_iterations_implicit_CN = 1e-10
filter_passes = 3
filter_alpha = 0.5
filter_strides = [1, 2, 4]

[solver_parameters]
field_solver = 0
time_evolution_algorithm = 0
number_grid_points = 120
number_pseudoelectrons = 12000
total_steps = 5000
max_number_of_Picard_iterations_implicit_CN = 12
number_of_particle_substeps_implicit_CN = 2
